openmessaging/dledger

- src/main/java/io/openmessaging/storage/dledger/DLedger.java
一个shutdown hook 在整个runtime只会调用一次，无需记录shutdown次数。 另外，shutdownTimes不存在同步问题，不需要AtomicInteger。
> delete extra variable

- src/main/java/io/openmessaging/storage/dledger/DLedgerConfig.java
- src/main/java/io/openmessaging/storage/dledger/DLedgerEntryPusher.java
- src/main/java/io/openmessaging/storage/dledger/DLedgerLeaderElector.java
- src/main/java/io/openmessaging/storage/dledger/DLedgerRpcNettyService.java
- src/main/java/io/openmessaging/storage/dledger/DLedgerServer.java
- src/main/java/io/openmessaging/storage/dledger/MemberState.java
- src/main/java/io/openmessaging/storage/dledger/client/DLedgerClient.java
- src/main/java/io/openmessaging/storage/dledger/client/DLedgerClientRpcNettyService.java
- src/main/java/io/openmessaging/storage/dledger/cmdline/BossCommand.java
- src/main/java/io/openmessaging/storage/dledger/cmdline/LeadershipTransferCommand.java
- src/main/java/io/openmessaging/storage/dledger/protocol/DLedgerClientProtocol.java
- src/main/java/io/openmessaging/storage/dledger/protocol/DLedgerClientProtocolHandler.java
- src/main/java/io/openmessaging/storage/dledger/protocol/DLedgerProtocol.java
- src/main/java/io/openmessaging/storage/dledger/protocol/DLedgerProtocolHander.java
- src/main/java/io/openmessaging/storage/dledger/protocol/DLedgerRequestCode.java
- src/main/java/io/openmessaging/storage/dledger/protocol/DLedgerResponseCode.java
- src/main/java/io/openmessaging/storage/dledger/protocol/LeadershipTransferRequest.java
- src/main/java/io/openmessaging/storage/dledger/protocol/LeadershipTransferResponse.java
- src/main/java/io/openmessaging/storage/dledger/protocol/VoteResponse.java
- src/main/java/io/openmessaging/storage/dledger/store/DLedgerMemoryStore.java
- src/main/java/io/openmessaging/storage/dledger/store/file/DLedgerMmapFileStore.java
- src/main/resources/log4j.properties
- src/test/java/io/openmessaging/storage/dledger/LeaderElectorTest.java
- src/test/java/io/openmessaging/storage/dledger/ServerTestHarness.java
Preferred Leader implementation.
Also add the leadership transfer command in BossCommand. Using the following command, we can transfer leadership from n0 to n1 on term 1.
`java -jar target/DLedger.jar leadershipTransfer -p "n0-localhost:20911;n1-localhost:20912;n2-localhost:20913" -l n0 -t n1 --term 1`
> Prefered leader

- src/main/java/io/openmessaging/storage/dledger/DLedgerLeaderElector.java
- src/test/java/io/openmessaging/storage/dledger/LeaderElectorTest.java
- src/test/java/io/openmessaging/storage/dledger/ServerTestHarness.java
Dledger can solve the problem of symmetric network partition at present, but it still cannot solve the problem of asymmetric network partition. For example, n1 and n2 can not communicate with each other, n2 and n3 can communicate with each other.
Dledger当前能解决对称网络分区的问题，但是当前还无法解决非对称网络分区的问题，举一个例子：n1和n2之间无法通信，但n2与n3可以通信。
When n2 does not receive the heartbeat, it will become candidate, then ask for vote. n3 will return  REJECT_ALREADY__HAS_LEADER, resulting in n2 setting the voting result to WAIT_TO_VOTE_NEXT . Then term increasing next round, which will result in the re-election of the cluster all the time.
n2没有收到心跳以后，会变成candidate，然后发起投票，n3返回REJECT_ALREADY__HAS_LEADER，导致n2设置投票结果为WAIT_TO_VOTE_NEXT，term增大，接着会造成集群的一直重新选举。
Simulate asymmetric network partition in my machines by using the …
> Polish network partition

- src/main/java/io/openmessaging/storage/dledger/DLedgerLeaderElector.java
- src/main/java/io/openmessaging/storage/dledger/DLedgerServer.java
- src/main/java/io/openmessaging/storage/dledger/MemberState.java
This PR is to polish preferedleader.
优化preferedleader
- The current situation is that REJECT_TAKING_LEADERSHIP may occur even if preferred leader is not set. So currTerm is initially set to 0 and termToTakeLeadership is initially set to -1, which ensures that they will not be the same under normal circumstances.
在测试的时候出现即使没有设置preferred leader，日志中仍然出现了REJECT_TAKING_LEADERSHIP。这是因为当前currTerm初始时设置为-1，而termToTakeLeadership设置为0，当term增加，两者会相等。因此设置currterm初始为0，termToTakeLeadership初始为-1，确保两者正常情况下不会相等。
- Role may be follower when term < TermToTakeLeadership in check function , it should not return directly. For example, The node may receive heartbeat before term increase as a candidate, then it will be follower and should return TAKE_LEADERSHIP_FAILED.
在TakeLeadershipTask的check方法中，当term …
> Polish preferedleader

- src/main/java/io/openmessaging/storage/dledger/DLedgerLeaderElector.java
In jepsen test, the cluster may be re-elected after network heal. This is because the last vote result was not reset, causing some nodes to increase term after the network partition.
when the node become follower, the last vote is reset to WAIT_TO_REVOTE
> Fix(elector):fix the issue that re-election after network heal

- src/main/java/io/openmessaging/storage/dledger/MemberState.java
K8s pod address always has "-" in its domain, so should change the peer address obtain strategy to satisfy this rule.
> Fix the address get logic for k8s pod domain name

- src/main/java/io/openmessaging/storage/dledger/DLedgerConfig.java
- src/main/java/io/openmessaging/storage/dledger/DLedgerLeaderElector.java
- src/main/java/io/openmessaging/storage/dledger/DLedgerServer.java
- src/main/java/io/openmessaging/storage/dledger/MemberState.java
In the implementation of preferred leader, if leader transfer occur during the failure period, the service will be unavailable during the whole failure phase. Because append is rejected when transferring.
So we need to avoid leader transferring during the failure period. In jepsen test, it is found that lead transfer occurred during the failure period because the water mark of preferred leader  is - 1 and fallBeind is less than MaxLeadershipTransferWaitIndex.
Add peersLiveTable for the leader, the leader gets information about the survival of other nodes through heartbeat. When preferred leader fails, leader avoids transferring to the node.
> Fix(preferredLeader):fix the issue that services maybe unavailable all the time when network partition happen

- src/main/java/io/openmessaging/storage/dledger/DLedgerConfig.java
- src/main/java/io/openmessaging/storage/dledger/DLedgerEntryPusher.java
- src/main/java/io/openmessaging/storage/dledger/protocol/PushEntryRequest.java
- src/test/java/io/openmessaging/storage/dledger/AppendAndGetTest.java
- src/test/java/io/openmessaging/storage/dledger/BatchPushTest.java
- src/test/java/io/openmessaging/storage/dledger/ServerTestHarness.java
link #44 
Users can enable batch replication by setting isEnableBatchPush to true, and batch replication will not affect the delay of a single request.
> [ISSUE #44] Add bulk copy support

- src/main/java/io/openmessaging/storage/dledger/DLedgerEntryPusher.java
Sort `peerWaterMarks` in descending order, and  `quorumIndex` is elems[len / 2]
> Change a way to calculate quorumIndex

- src/main/java/io/openmessaging/storage/dledger/MemberState.java
An error condition：
dLegerPeers=n9-xxx;n10-xxx;n11-xxx
> [bug]fix peers different length case

- src/main/java/io/openmessaging/storage/dledger/store/file/DLedgerMmapFileStore.java
- src/test/java/io/openmessaging/storage/dledger/store/DLedgerManagedFileStoreTruncateTest.java
when truncate there is always warn log like "Offset not matched. Request offset: {}, firstOffset: {}, lastOffset: {}, mappedFileSize: {}, mappedFiles count".
> [Fix] DLedgerMmapFileStore move flushedWhere pos after truncate file.

- src/main/java/io/openmessaging/storage/dledger/DLedgerEntryPusher.java
#87 
**Brief changelog**
- When the message append is abnormal, perform the compare again.
> [ISSUE 87] Fix the expiration problem of the push message

- src/main/java/io/openmessaging/storage/dledger/DLedgerEntryPusher.java
- src/main/java/io/openmessaging/storage/dledger/protocol/PushEntryRequest.java
#94 
**Optimization logic**
According to the configuration enableBatchPush, choose whether to synchronize data through batch. When a push request is received, it is judged whether it is a batch push according to the number of messages sent.
> [ISSUE #94] Batch push compatible with single push

- src/main/java/io/openmessaging/storage/dledger/DLedgerEntryPusher.java
- src/main/java/io/openmessaging/storage/dledger/store/file/DLedgerMmapFileStore.java
Too much text, so I write in Chinese。
我发现rocketmq 在 dledger 模式下 性能不是很好，可以看：https://github.com/apache/rocketmq/issues/3315
rocketmq， 4.9.1 ，16c， 32g   ，1wtps，p99 很难到达 2ms 以下，最好的情况也需要 3ms。
我重新编译了代码发现瓶颈在 raft 同步数据上，写完pageccache 后等待同步完成平均需要 1.7ms。
我在dledger 代码中发现了几个问题，我尝试修改了dledger 的代码，之后进行了测试，3wtps 下 p99 到达了 1-2ms。
平均耗时 0.8-1ms。大约提升了1ms。
修改项：
1.
src/main/java/io/openmessaging/storage/dledger/DLedgerEntryPusher.java  745 
将waitForRunning(1);  改为 Thread.yield();
设计思想应该是 如果一直有消息进入推动 dLedgerStore.getLedgerEndIndex() 的数值变大，就不会break 循环去执行waitForRunning(1); 
但经过我的测试 在 1w tps  下 waitForRunning(1); 执行的非常频繁每次都会休眠 1ms ，因为有新消息时并不会 wakeup(); 唤醒线程。我猜可能是 getLedgerEndIndex() 访问的  ledgerEndIndex 属性没有被 volatile 修饰？
481行
if (writeIndex > dLedgerStore.getLedgerEndIndex()) { 
doCommit();
doCheckAppendResponse(); …
> [ISSUE #97] Performance optimization

- src/main/java/io/openmessaging/storage/dledger/DLedgerConfig.java
- src/main/java/io/openmessaging/storage/dledger/DLedgerLeaderElector.java
- src/main/java/io/openmessaging/storage/dledger/DLedgerServer.java
- src/test/java/io/openmessaging/storage/dledger/AppendAndGetTest.java
- src/test/java/io/openmessaging/storage/dledger/BatchPushTest.java
- src/test/java/io/openmessaging/storage/dledger/LeaderElectorTest.java
#90 
- Support setting multiple preferredLeaders, separated by ';', compatible with a single situation
- Multiple preferredLeaders, randomly select one of them for processing
> [ISSUE #90] suppport multiple preferred leader

- src/main/java/io/openmessaging/storage/dledger/store/file/DLedgerMmapFileStore.java
For issue #103 
The variable `DLedgerMmapFileStore#isDiskFull` should be decorated with the **volatile**,
because it will be written by the thread `CleanSpaceService`, and it will be read by other threads when append `DLedgerEntry`.
> The variable DLedgerMmapFileStore#isDiskFull should be decorated with the volatile.

- src/main/java/io/openmessaging/storage/dledger/DLedgerConfig.java
- src/main/java/io/openmessaging/storage/dledger/DLedgerServer.java
#85 
- Add verification to the preferredLeader node to avoid node unavailability caused by ledger falling behind.
- Added leadershipTransferWaitTimeout. When the ledger cannot catch up within the time threshold, return DLedgerResponseCode.TAKE_LEADERSHIP_FAILED.
> [ISSUE #85] fix preferred leader bug

- src/main/java/io/openmessaging/storage/dledger/DLedgerServer.java
For issue #111 
- In method `DLedgerServer#checkPreferredLeader()`, The first peer in the list `preferredLeaderIds` that meets the condition is determined to be the leader `transferee`
- I think, the peer with the smallest lag(fall behind index) be the `transferee`, which may be better.
> [ISSUE #111] It is better for the peer with the smallest lag(fall behind index) to become the transferee.

- src/main/java/io/openmessaging/storage/dledger/DLedgerConfig.java
- src/main/java/io/openmessaging/storage/dledger/store/file/DLedgerMmapFileStore.java
- src/main/java/io/openmessaging/storage/dledger/store/file/MmapFileList.java
- src/main/java/io/openmessaging/storage/dledger/store/file/MultiPathMmapFileList.java
- src/main/java/io/openmessaging/storage/dledger/utils/DLedgerUtils.java
> [ISSUE #118] Support multi-dirs storage

- src/main/java/io/openmessaging/storage/dledger/DLedgerRpcService.java
- src/main/java/io/openmessaging/storage/dledger/DLedgerServer.java
- src/main/java/io/openmessaging/storage/dledger/protocol/DLedgerProtocolHandler.java
renamed DLedgerProtocolHander to DLedgerProtocolHandler. #126
> [ISSUE #126] The class DLedgerProtocolHander name should be DLedgerProtocolHandler

- src/main/java/io/openmessaging/storage/dledger/DLedgerEntryPusher.java
- src/main/java/io/openmessaging/storage/dledger/DLedgerServer.java
- src/main/java/io/openmessaging/storage/dledger/snapshot/SnapshotReader.java
- src/main/java/io/openmessaging/storage/dledger/snapshot/SnapshotWriter.java
- src/main/java/io/openmessaging/storage/dledger/statemachine/CommittedEntryIterator.java
- src/main/java/io/openmessaging/storage/dledger/statemachine/StateMachine.java
- src/main/java/io/openmessaging/storage/dledger/statemachine/StateMachineCaller.java
- src/test/java/io/openmessaging/storage/dledger/statemachine/MockStateMachine.java
- src/test/java/io/openmessaging/storage/dledger/statemachine/StateMachineCallerTest.java
Add a state machine for dledger, support apply, snapshotSave, snapshotLoad.
> Feature: add statemachine for dledger

- src/main/java/io/openmessaging/storage/dledger/DLedgerEntryPusher.java
- src/main/java/io/openmessaging/storage/dledger/DLedgerServer.java
- src/main/java/io/openmessaging/storage/dledger/snapshot/SnapshotReader.java
- src/main/java/io/openmessaging/storage/dledger/snapshot/SnapshotWriter.java
- src/main/java/io/openmessaging/storage/dledger/statemachine/CommittedEntryIterator.java
- src/main/java/io/openmessaging/storage/dledger/statemachine/StateMachine.java
- src/main/java/io/openmessaging/storage/dledger/statemachine/StateMachineCaller.java
- src/test/java/io/openmessaging/storage/dledger/statemachine/MockStateMachine.java
- src/test/java/io/openmessaging/storage/dledger/statemachine/StateMachineCallerTest.java
Add Statemachine feature for DLedger
> Add Statemachine feature for DLedger

- pom.xml
Update slf4j-log4j12 dependency to the newest stable released version to fix vulnerabilities within the original version.
> Update org.slf4j-log4j12@1.7.6 to org.slf4j-log4j12@1.7.36

- src/main/java/io/openmessaging/storage/dledger/statemachine/StateMachineCaller.java
Make StateMachineCaller thread will not exit when throw exception
> Make StateMachineCaller thread will not exit when throw exception

- src/main/java/io/openmessaging/storage/dledger/client/DLedgerClient.java
Fix[159](https://github.com/openmessaging/dledger/issues/159)DLedgerClient the log format is incorrect
> [ISSUE#159] fix DLedgerClient the log format is incorrect

- pom.xml
[Fix 177 issue](https://github.com/openmessaging/dledger/issues/177)
- upgrade rocketmq-remoting version,NettyRemotingClient.createChannel method has a bug in high concurrency
> [ISSUE #177] update rocketmq-remoting version 4.3.2 to 4.9.4

- pom.xml
- src/main/java/io/openmessaging/storage/dledger/store/file/DLedgerMmapFileStore.java
Add a lightweight log implementation slf4j-simple, so that the dledger can output logs when running independently
> Add a lightweight log implementation slf4j-simple

- src/main/java/io/openmessaging/storage/dledger/DLedger.java
- src/main/java/io/openmessaging/storage/dledger/cmdline/BossCommand.java
- src/main/java/io/openmessaging/storage/dledger/cmdline/GetCommand.java
- src/main/java/io/openmessaging/storage/dledger/cmdline/LeadershipTransferCommand.java
- src/main/java/io/openmessaging/storage/dledger/cmdline/ReadFileCommand.java
- src/main/java/io/openmessaging/storage/dledger/cmdline/ServerCommand.java
Fix #192 
- Optimize BossCommand code and add ServerCommand
- GetCommand，LeadershipTransferCommand，ReadFileCommand add Parameters annotation and add command description for each.（Tips: AppendCommand command description was added in this PR #188 ）
```shell
Usage: <main class> [command] [command options]
Commands:
server      Bootstrap DLedger Server
Usage: server [options]
Options:
--group, -g
Group of this server
Default: default
--id, -i
Self id of this server
Default: n0
--peer-push-quotas
The quotas of the pusher
Default: 20971520
--peer-push-throttle-point
When the follower is behind the leader more than this value, it 
will trigger the throttle
Default: 314572800
--peers, -p
Peer info of this server
Default: n0-localhost:20911
--preferred-leader-id
Preferred LeaderId …
```
> [ISSUE #192]Optimize BossCommand code and add ServerCommand

- src/main/java/io/openmessaging/storage/dledger/store/file/DefaultMmapFile.java
- src/test/java/io/openmessaging/storage/dledger/store/file/DefaultMmapFileTest.java
Fix #189 
-  DefaultMmapFile memory usage Optimize
> [ISSUE #189] DefaultMmapFile memory usage Optimize

- dledger/src/main/java/io/openmessaging/storage/dledger/DLedgerConfig.java
- dledger/src/main/java/io/openmessaging/storage/dledger/DLedgerServer.java
- dledger/src/main/java/io/openmessaging/storage/dledger/store/file/DLedgerMmapFileStore.java
Do not enable clean space service after registering the state machine
> [ISSUE #236] Do not enable clean space service after registering the state machine

- command/src/main/java/io/openmessaging/storage/dledger/command/LeadershipTransferCommand.java
- dledger/src/main/java/io/openmessaging/storage/dledger/DLedgerEntryPusher.java
- dledger/src/main/java/io/openmessaging/storage/dledger/DLedgerLeaderElector.java
- dledger/src/main/java/io/openmessaging/storage/dledger/DLedgerRpcNettyService.java
- dledger/src/main/java/io/openmessaging/storage/dledger/DLedgerServer.java
- dledger/src/main/java/io/openmessaging/storage/dledger/MemberState.java
- dledger/src/main/java/io/openmessaging/storage/dledger/NamedThreadFactory.java
- dledger/src/main/java/io/openmessaging/storage/dledger/ShutdownAbleThread.java
- dledger/src/main/java/io/openmessaging/storage/dledger/client/DLedgerClient.java
- dledger/src/main/java/io/openmessaging/storage/dledger/client/DLedgerClientRpcNettyService.java
- dledger/src/main/java/io/openmessaging/storage/dledger/client/DLedgerClientRpcService.java
- dledger/src/main/java/io/openmessaging/storage/dledger/store/DLedgerMemoryStore.java
- dledger/src/main/java/io/openmessaging/storage/dledger/store/file/DLedgerMmapFileStore.java
- dledger/src/main/java/io/openmessaging/storage/dledger/store/file/DefaultMmapFile.java
- dledger/src/main/java/io/openmessaging/storage/dledger/store/file/MmapFileList.java
- dledger/src/main/java/io/openmessaging/storage/dledger/utils/IOUtils.java
- proxy/src/main/java/io/openmessaging/storage/dledger/proxy/ConfigManager.java
- proxy/src/main/java/io/openmessaging/storage/dledger/proxy/DLedgerManager.java
- proxy/src/main/java/io/openmessaging/storage/dledger/proxy/DLedgerProxy.java
> code styles fix

- dledger/src/main/java/io/openmessaging/storage/dledger/DLedgerEntryPusher.java
- dledger/src/main/java/io/openmessaging/storage/dledger/snapshot/SnapshotManager.java
- dledger/src/main/java/io/openmessaging/storage/dledger/snapshot/file/FileSnapshotWriter.java
- dledger/src/main/java/io/openmessaging/storage/dledger/statemachine/StateMachineCaller.java
- dledger/src/main/java/io/openmessaging/storage/dledger/store/DLedgerMemoryStore.java
- dledger/src/main/java/io/openmessaging/storage/dledger/store/DLedgerStore.java
- dledger/src/main/java/io/openmessaging/storage/dledger/store/file/DLedgerMmapFileStore.java
- dledger/src/test/java/io/openmessaging/storage/dledger/AppendAndPushTest.java
- dledger/src/test/java/io/openmessaging/storage/dledger/BatchPushTest.java
- dledger/src/test/java/io/openmessaging/storage/dledger/snapshot/SnapshotManagerTest.java
- dledger/src/test/java/io/openmessaging/storage/dledger/statemachine/MockStateMachine.java
- dledger/src/test/java/io/openmessaging/storage/dledger/store/DLedgerMappedFileStoreTest.java
> [ISSUE#268]Fix wrong ledgerIndex and wrong generated snapshot in snapshot mode

- dledger/src/main/java/io/openmessaging/storage/dledger/DLedgerEntryPusher.java
- dledger/src/main/java/io/openmessaging/storage/dledger/statemachine/StateMachineCaller.java
- dledger/src/main/java/io/openmessaging/storage/dledger/store/file/DLedgerMmapFileStore.java
1. fix the bug because of enqueueing an unchecked commit task
Closes https://github.com/openmessaging/dledger/issues/278
> [ISSUE #278] Fix the bug because of enqueueing an unchecked commit task

- dledger/src/main/java/io/openmessaging/storage/dledger/DLedgerConfig.java
- dledger/src/main/java/io/openmessaging/storage/dledger/DLedgerServer.java
- dledger/src/main/java/io/openmessaging/storage/dledger/statemachine/StateMachineCaller.java
- dledger/src/test/java/io/openmessaging/storage/dledger/AppendAndReadTest.java
- dledger/src/test/java/io/openmessaging/storage/dledger/ServerTestHarness.java
- dledger/src/test/java/io/openmessaging/storage/dledger/snapshot/SnapshotManagerTest.java
- dledger/src/test/java/io/openmessaging/storage/dledger/statemachine/StateMachineCallerTest.java
1. add switch to enable/disable snapshot feature
Closes https://github.com/openmessaging/dledger/issues/290
> [ISSUE #290]: add switch to enable/disable snapshot feature

- README.md
> [ISSUE #292] Update current quick-start

- dledger/src/main/java/io/openmessaging/storage/dledger/DLedgerEntryPusher.java
- dledger/src/main/java/io/openmessaging/storage/dledger/DLedgerServer.java
- dledger/src/main/java/io/openmessaging/storage/dledger/common/WriteClosure.java
- dledger/src/main/java/io/openmessaging/storage/dledger/common/WriteTask.java
- dledger/src/main/java/io/openmessaging/storage/dledger/statemachine/ApplyEntry.java
- dledger/src/main/java/io/openmessaging/storage/dledger/statemachine/ApplyEntryIterator.java
- dledger/src/main/java/io/openmessaging/storage/dledger/statemachine/ApplyTask.java
- dledger/src/main/java/io/openmessaging/storage/dledger/statemachine/NoOpStatemachine.java
- dledger/src/main/java/io/openmessaging/storage/dledger/statemachine/StateMachine.java
- dledger/src/main/java/io/openmessaging/storage/dledger/statemachine/StateMachineCaller.java
- dledger/src/test/java/io/openmessaging/storage/dledger/WriteTest.java
- dledger/src/test/java/io/openmessaging/storage/dledger/statemachine/MockStateMachine.java
- dledger/src/test/java/io/openmessaging/storage/dledger/statemachine/StateMachineCallerTest.java
- dledger/src/test/java/io/openmessaging/storage/dledger/statemachine/register/RegisterStateMachine.java
- example/src/main/java/io/openmessaging/storage/dledger/example/register/RegisterStateMachine.java
- proxy/src/main/java/io/openmessaging/storage/dledger/proxy/DLedgerProxy.java
close: https://github.com/openmessaging/dledger/issues/303
> [ISSUE #303] Support upper layer write entry and get response data when entry is applied

- dledger/src/main/java/io/openmessaging/storage/dledger/DLedgerConfig.java
- dledger/src/main/java/io/openmessaging/storage/dledger/DLedgerEntryPusher.java
- dledger/src/main/java/io/openmessaging/storage/dledger/DLedgerServer.java
- dledger/src/main/java/io/openmessaging/storage/dledger/MemberState.java
- dledger/src/main/java/io/openmessaging/storage/dledger/common/Status.java
- dledger/src/main/java/io/openmessaging/storage/dledger/statemachine/ApplyEntryIterator.java
- dledger/src/test/java/io/openmessaging/storage/dledger/AppendAndGetTest.java
- dledger/src/test/java/io/openmessaging/storage/dledger/AppendAndReadTest.java
- dledger/src/test/java/io/openmessaging/storage/dledger/CommitIndexTest.java
- dledger/src/test/java/io/openmessaging/storage/dledger/LeaderElectorTest.java
- dledger/src/test/java/io/openmessaging/storage/dledger/ServerTestHarness.java
- dledger/src/test/java/io/openmessaging/storage/dledger/store/DLedgerMappedFileStoreTest.java
close: https://github.com/openmessaging/dledger/issues/305
> [ISSUE #305] Support fast advance commit index by appending no-op entry

- dledger/src/main/java/io/openmessaging/storage/dledger/DLedgerEntryPusher.java
- dledger/src/main/java/io/openmessaging/storage/dledger/statemachine/StateMachineCaller.java
- dledger/src/test/java/io/openmessaging/storage/dledger/AppendAndPushTest.java
- dledger/src/test/java/io/openmessaging/storage/dledger/BatchPushTest.java
- dledger/src/test/java/io/openmessaging/storage/dledger/ServerTestHarness.java
Change-Id: I24b4cc67d66d7fba3ae4c46480da1af1c769479d
Fix some possible memory leak:
1. timeout response check should remove map index
2. follower should check and clean old pending closure since it may changed from leader which will has old data
> fix: follower should try clean pending closure to avoid memory leak

- dledger/src/main/java/io/openmessaging/storage/dledger/DLedgerEntryPusher.java
- dledger/src/main/java/io/openmessaging/storage/dledger/DLedgerRpcNettyService.java
- dledger/src/main/java/io/openmessaging/storage/dledger/DLedgerServer.java
- dledger/src/main/java/io/openmessaging/storage/dledger/MemberState.java
- dledger/src/main/java/io/openmessaging/storage/dledger/common/WriteClosure.java
- dledger/src/main/java/io/openmessaging/storage/dledger/snapshot/SnapshotManager.java
- dledger/src/main/java/io/openmessaging/storage/dledger/statemachine/StateMachine.java
- dledger/src/main/java/io/openmessaging/storage/dledger/store/file/MmapFile.java
- dledger/src/test/java/io/openmessaging/storage/dledger/WriteTest.java
- dledger/src/test/java/io/openmessaging/storage/dledger/statemachine/StateMachineCallerTest.java
> [ISSUE #310] Fix to successfully generate java doc
