openmessaging/dledger

src/main/java/io/openmessaging/storage/dledger/DLedger.java
src/main/java/io/openmessaging/storage/dledger/utils/ResettableCountDownLatch.java

simplify the code and minor typo fix

simplify the code and minor typo fix

---

.travis.yml

Fix travis jdk_swither not found exception

Fix travis jdk_swither not found exception

---

README.md
docs/cn/introduction_dledger.md

Docs(readme):polish readme doc

---

README.md

Add maven central badge to readme doc.

chore(readme):add maven central badge to readme doc

---

src/main/java/io/openmessaging/storage/dledger/DLedgerLeaderElector.java
src/main/java/io/openmessaging/storage/dledger/DLedgerRpcNettyService.java

[ISSUE #42] Fix rpc module null pointer exception handling

---

src/main/java/io/openmessaging/storage/dledger/DLedgerEntryPusher.java
src/main/java/io/openmessaging/storage/dledger/protocol/DLedgerResponseCode.java
src/main/java/io/openmessaging/storage/dledger/store/file/DLedgerMmapFileStore.java
src/test/java/io/openmessaging/storage/dledger/store/DLedgerMappedFileStoreTest.java

In case the requested index was cleaned by CleanSpaceService, try auto recovery.

[ISSUE RocketMQ#1778]

---

src/main/java/io/openmessaging/storage/dledger/store/DLedgerMemoryStore.java
src/main/java/io/openmessaging/storage/dledger/store/file/DLedgerMmapFileStore.java

[ISSUE #52] make ledgerEndTerm be equals with logs term if it is not leader

---

src/main/java/io/openmessaging/storage/dledger/DLedgerLeaderElector.java

volatile needIncreaseTermImmediately

---

src/main/java/io/openmessaging/storage/dledger/client/DLedgerClient.java
src/main/java/io/openmessaging/storage/dledger/client/DLedgerClientRpcService.java

[ISSUE #68] Fix peers parsing error

---

src/main/java/io/openmessaging/storage/dledger/DLedgerEntryPusher.java

[ISSUE #70] Log when quota exhaust

---

src/main/java/io/openmessaging/storage/dledger/DLedgerLeaderElector.java
src/main/java/io/openmessaging/storage/dledger/DLedgerRpcNettyService.java

Fix the heartbeat and voting block caused by invokeAsync.

 Fix the heartbeat and voting block caused by invokeAsync

---

src/main/java/io/openmessaging/storage/dledger/DLedgerLeaderElector.java

Polish the election process
优化选举
当`有效的票数`减去`日志比自己新的票数`值小于qurom时，此时不应该增加term。因为即使term增加，下一轮选举也不太能被选为leader，此时将机会应该让给日志最新的节点。

enhancement(elector): polish the election process

---

src/main/java/io/openmessaging/storage/dledger/DLedgerEntryPusher.java

optimize code

---

src/main/java/io/openmessaging/storage/dledger/BatchAppendFuture.java
src/main/java/io/openmessaging/storage/dledger/DLedgerEntryPusher.java

fix single node with error response when batch append

fix single node with error response when batch append

---

src/main/java/io/openmessaging/storage/dledger/ApplyTask.java
src/main/java/io/openmessaging/storage/dledger/DLedgerConfig.java
src/main/java/io/openmessaging/storage/dledger/DLedgerEntryPusher.java
src/main/java/io/openmessaging/storage/dledger/DLedgerRpcNettyService.java
src/main/java/io/openmessaging/storage/dledger/DLedgerServer.java
src/main/java/io/openmessaging/storage/dledger/client/DLedgerClientRpcNettyService.java
src/main/java/io/openmessaging/storage/dledger/fsm/StateMachine.java
src/main/java/io/openmessaging/storage/dledger/fsm/StateMachineInvoker.java
src/main/java/io/openmessaging/storage/dledger/fsm/StateMachineInvokerImpl.java
src/main/java/io/openmessaging/storage/dledger/protocol/ApplyTaskRequest.java
src/main/java/io/openmessaging/storage/dledger/protocol/ApplyTaskResponse.java
src/main/java/io/openmessaging/storage/dledger/protocol/DLedgerRequestCode.java
src/main/java/io/openmessaging/storage/dledger/protocol/InstallSnapshotRequest.java
src/main/java/io/openmessaging/storage/dledger/protocol/VoteResponse.java
src/main/java/io/openmessaging/storage/dledger/store/snapshot/Snapshot.java
src/main/java/io/openmessaging/storage/dledger/store/snapshot/SnapshotManager.java
src/main/java/io/openmessaging/storage/dledger/store/snapshot/SnapshotReader.java
src/main/java/io/openmessaging/storage/dledger/store/snapshot/SnapshotStore.java
src/main/java/io/openmessaging/storage/dledger/store/snapshot/SnapshotWriter.java
src/main/resources/log4j.properties

Add state machine for dledger.

Add state machine for dledger.

---

src/main/java/io/openmessaging/storage/dledger/DLedgerRpcNettyService.java
src/main/java/io/openmessaging/storage/dledger/ShutdownAbleThread.java
src/main/java/io/openmessaging/storage/dledger/protocol/HeartBeatResponse.java
src/main/java/io/openmessaging/storage/dledger/protocol/LeadershipTransferResponse.java
src/main/java/io/openmessaging/storage/dledger/store/DLedgerMemoryStore.java
src/main/java/io/openmessaging/storage/dledger/store/file/DLedgerMmapFileStore.java
src/main/java/io/openmessaging/storage/dledger/store/file/DefaultMmapFile.java
src/main/java/io/openmessaging/storage/dledger/store/file/MmapFileList.java
src/main/java/io/openmessaging/storage/dledger/store/file/ReferenceResource.java
src/main/java/io/openmessaging/storage/dledger/utils/DLedgerUtils.java
src/main/java/io/openmessaging/storage/dledger/utils/IOUtils.java
src/main/java/io/openmessaging/storage/dledger/utils/ResettableCountDownLatch.java

Link [issues-116](https://github.com/openmessaging/dledger/issues/116).

[ISSUE-116] Some class's method lost annotation 'Override'.

---

pom.xml
src/test/java/io/openmessaging/storage/dledger/AppendAndGetTest.java
src/test/java/io/openmessaging/storage/dledger/AppendAndPushTest.java
src/test/java/io/openmessaging/storage/dledger/BatchPushTest.java
src/test/java/io/openmessaging/storage/dledger/DLedgerConfigTest.java
src/test/java/io/openmessaging/storage/dledger/LeaderElectorTest.java
src/test/java/io/openmessaging/storage/dledger/ServerTestBase.java
src/test/java/io/openmessaging/storage/dledger/entry/DLedgerEntryCoderTest.java
src/test/java/io/openmessaging/storage/dledger/protocol/HeartbeatRequestTest.java
src/test/java/io/openmessaging/storage/dledger/protocol/VoteRequestTest.java
src/test/java/io/openmessaging/storage/dledger/store/DLedgerManagedFileStoreTruncateTest.java
src/test/java/io/openmessaging/storage/dledger/store/DLedgerMappedFileStoreTest.java
src/test/java/io/openmessaging/storage/dledger/store/MmapFileListTest.java
src/test/java/io/openmessaging/storage/dledger/util/QuotaTest.java

Bump junit to 5.8.2.[ISSUE-114](https://github.com/openmessaging/dledger/issues/113)

[ISSUE-114] Bump junit to 5.8.2.

---

src/main/java/io/openmessaging/storage/dledger/store/file/MmapFileList.java

[ISSUE #120] fix check style error

---

src/main/java/io/openmessaging/storage/dledger/DLedgerEntryPusher.java
src/main/java/io/openmessaging/storage/dledger/store/file/MmapFileList.java

[ISSUE #122] fix high CPU in EntryDispatcher

---

src/main/java/io/openmessaging/storage/dledger/DLedgerEntryPusher.java

Fix https://github.com/openmessaging/dledger/issues/134

[ISSUE #134] fix batch push error

---

src/main/java/io/openmessaging/storage/dledger/DLedgerEntryPusher.java
src/main/java/io/openmessaging/storage/dledger/DLedgerServer.java
src/main/java/io/openmessaging/storage/dledger/statemachine/StateMachineCaller.java

fix bug in statemachine mode:
1.checkResponseFuture Timeout from quorumIndex + 1
2. init fsmCaller to empty()

BugFix: fix bug in statemachine mode

---

src/main/java/io/openmessaging/storage/dledger/DLedgerEntryPusher.java
src/main/java/io/openmessaging/storage/dledger/protocol/PushEntryRequest.java
src/main/java/io/openmessaging/storage/dledger/protocol/PushEntryResponse.java

[ISSUE #140] fix obtain pair from batchPendingMap

---

src/main/java/io/openmessaging/storage/dledger/DLedgerEntryPusher.java

[ISSUE #142] fix replica cannot be synced

---

src/main/java/io/openmessaging/storage/dledger/DLedgerRpcNettyService.java
src/main/java/io/openmessaging/storage/dledger/DLedgerServer.java

1.Expose NettyRemotingServer, so that the upper layer can reuse this remotingServer.
2.add constructor in DledgerServer

Expose nettyRemotingServer

---

src/main/java/io/openmessaging/storage/dledger/DLedgerLeaderElector.java
src/main/java/io/openmessaging/storage/dledger/DLedgerServer.java
src/main/java/io/openmessaging/storage/dledger/client/DLedgerClientRpcNettyService.java
src/main/java/io/openmessaging/storage/dledger/store/file/DLedgerMmapFileStore.java
src/main/java/io/openmessaging/storage/dledger/store/file/DefaultMmapFile.java

Fix:[157](https://github.com/openmessaging/dledger/issues/157)
total 5 class code format problem

[ISSUE #157] fix code format problem

---

src/main/java/io/openmessaging/storage/dledger/DLedgerEntryPusher.java

[ISSUE #162] fix sync stopped when upgrade 0.2.6 from 0.2.2

---

src/main/java/io/openmessaging/storage/dledger/DLedgerRpcNettyService.java
src/main/java/io/openmessaging/storage/dledger/DLedgerServer.java
src/main/java/io/openmessaging/storage/dledger/NamedThreadFactory.java
src/test/java/io/openmessaging/storage/dledger/NamedThreadFactoryTest.java

[[Fix 161](https://github.com/openmessaging/dledger/issues/161)] -optimize the thread pool ThreadFactory implementation

[ISSUE#161]optimize the thread pool ThreadFactory implementation

---

src/main/java/io/openmessaging/storage/dledger/utils/ResettableCountDownLatch.java

@see are not redirected correctly, line breaks before @see, or use {@link ...}

use {@link ...} to be redirected correctly

---

style/dledger_codestyle.xml

[Fix issue 180](https://github.com/openmessaging/dledger/issues/180) Method is on the same line as @Override code style issue

[ISSUE #180]fix Method is on the same line as @Override code style issue

---

src/main/java/io/openmessaging/storage/dledger/DLedgerLeaderElector.java

Fix #191 
- Optimize DLedgerLeaderElector.maintainAsCandidate code

[ISSUE #191]Optimize DLedgerLeaderElector.maintainAsCandidate code

---

src/main/java/io/openmessaging/storage/dledger/store/file/DLedgerMmapFileStore.java

Fix #185 
- Fix DLedgerMmapFileStore#recover method throw java.nio.BufferUnderflowException

[ISSUE #185]  fix DLedgerMmapFileStore#recover method throw java.nio.BufferUnderflowException

---

src/main/java/io/openmessaging/storage/dledger/store/file/DefaultMmapFile.java

Fix #204 
-  Fix comment word typo

[ISSUE #204] Fix comment word typo

---

src/main/java/io/openmessaging/storage/dledger/cmdline/BossCommand.java

style(main): remove unused import

---

src/main/java/io/openmessaging/storage/dledger/cmdline/BossCommand.java
src/main/java/io/openmessaging/storage/dledger/cmdline/ServerCommand.java
src/main/java/io/openmessaging/storage/dledger/utils/ConfigUtils.java

issue: https://github.com/openmessaging/dledger/issues/208

feat(main): support starting up with config file

---

src/main/java/io/openmessaging/storage/dledger/DLedger.java

[ISSUE #210] Unable to Start DLedger without config.yaml

---

README.md
command/pom.xml
dledger/pom.xml
pom.xml

[ISSUE #215] Polish the pom file

---

command/pom.xml
dledger/pom.xml

Add ASF header to new pom file

[ISSUE #217] Add ASF header to new pom file

---

README.md
command/src/main/java/io/openmessaging/storage/dledger/command/AppendCommand.java
command/src/main/java/io/openmessaging/storage/dledger/command/BaseCommand.java
command/src/main/java/io/openmessaging/storage/dledger/command/BossCommand.java
command/src/main/java/io/openmessaging/storage/dledger/command/ConfigCommand.java
command/src/main/java/io/openmessaging/storage/dledger/command/DLedger.java
command/src/main/java/io/openmessaging/storage/dledger/command/GetCommand.java
command/src/main/java/io/openmessaging/storage/dledger/command/LeadershipTransferCommand.java
command/src/main/java/io/openmessaging/storage/dledger/command/ReadFileCommand.java
command/src/main/java/io/openmessaging/storage/dledger/command/ServerCommand.java
command/src/test/java/io/openmessaging/storage/dledger/command/DLedgerProxyConfigTest.java
dledger/src/main/java/io/openmessaging/storage/dledger/DLedgerEntryPusher.java
dledger/src/main/java/io/openmessaging/storage/dledger/DLedgerLeaderElector.java
dledger/src/main/java/io/openmessaging/storage/dledger/DLedgerServer.java
dledger/src/test/java/io/openmessaging/storage/dledger/store/file/DefaultMmapFileTest.java
proxy/pom.xml
proxy/src/test/java/io/openmessaging/storage/dledger/proxy/AppendAndGetTest.java
proxy/src/test/java/io/openmessaging/storage/dledger/proxy/AppendAndPushTest.java
proxy/src/test/java/io/openmessaging/storage/dledger/proxy/BatchPushTest.java
proxy/src/test/java/io/openmessaging/storage/dledger/proxy/LeaderElectorTest.java
proxy/src/test/java/io/openmessaging/storage/dledger/proxy/ProxyAppendAndGetTest.java
proxy/src/test/java/io/openmessaging/storage/dledger/proxy/ServerTestBase.java
proxy/src/test/java/io/openmessaging/storage/dledger/proxy/ServerTestHarness.java
proxy/src/test/java/io/openmessaging/storage/dledger/proxy/util/ConfigUtilsTest.java
proxy/src/test/java/io/openmessaging/storage/dledger/proxy/util/FileTestUtil.java

Polish the code after separating DLedgerProxy module

[ISSUE #221]Polish the code after separating DLedgerProxy module

---

dledger/src/main/java/io/openmessaging/storage/dledger/DLedgerEntryPusher.java
dledger/src/main/java/io/openmessaging/storage/dledger/statemachine/StateMachine.java

1. fix the append process when DLedger group only has one node

fix(main): fix the append process when DLedger group only has one node

---

pom.xml

close #231 
- Fix run DLedger Server with jar can't find Main class

[ISSUE #231]Fix run DLedger Server with jar can't find Main class

---

dledger/pom.xml
dledger/src/main/java/io/openmessaging/storage/dledger/store/file/DefaultMmapFile.java
pom.xml

[ISSUE #238] Fix illegal reflective access

---

dledger/src/main/java/io/openmessaging/storage/dledger/DLedgerLeaderElector.java
dledger/src/main/java/io/openmessaging/storage/dledger/DLedgerServer.java

[ISSUE #247]revote when leader's term is not the biggest

---

proxy/src/main/java/io/openmessaging/storage/dledger/proxy/ConfigManager.java

close #242 
- Remove useless variable

[ISSUE #242]Remove useless variable

---

dledger/src/main/java/io/openmessaging/storage/dledger/DLedgerEntryPusher.java

[ISSUE #251] Fix: checkAbnormalFuture of slave will not work if the network is abnormal

---

pom.xml

Add new plugin to auto release

[ISSUE #253] Add new plugin to auto release

---

proxy/src/main/java/io/openmessaging/storage/dledger/proxy/ConfigManager.java

[ISSUE #255] Remove useless import

---

dledger/src/main/java/io/openmessaging/storage/dledger/store/file/MmapFileList.java
dledger/src/test/java/io/openmessaging/storage/dledger/store/DLedgerMappedFileStoreTest.java

issue: https://github.com/openmessaging/dledger/issues/245

[ISSUE 245] fix wrong recover logic after reseting offset

---

dledger/src/main/java/io/openmessaging/storage/dledger/statemachine/StateMachineCaller.java
pom.xml

[ISSUE #276] Upgrade rocketmq remoting version to 5.1.0

---

dledger/src/main/java/io/openmessaging/storage/dledger/NamedThreadFactory.java

[ISSUE #272]Fix NamedThreadFactory attribute typo

---

dledger/src/main/java/io/openmessaging/storage/dledger/DLedgerEntryPusher.java
dledger/src/main/java/io/openmessaging/storage/dledger/statemachine/StateMachineCaller.java
dledger/src/main/java/io/openmessaging/storage/dledger/store/file/DLedgerMmapFileStore.java

1. fix commit without check
Closes https://github.com/openmessaging/dledger/issues/278

[ISSUE #278][master]: fix commit without check

---

dledger/src/main/java/io/openmessaging/storage/dledger/DLedgerEntryPusher.java

Change-Id: I608a1912120f124e15df75924ad2a14d8f523645
this fix #295

[ISSUE #295]fix: batch append should also checkQuotaAndWait

---

dledger/src/main/java/io/openmessaging/storage/dledger/DLedgerServer.java
dledger/src/main/java/io/openmessaging/storage/dledger/entry/DLedgerEntry.java
dledger/src/main/java/io/openmessaging/storage/dledger/entry/DLedgerEntryType.java
dledger/src/main/java/io/openmessaging/storage/dledger/statemachine/CommittedEntryIterator.java
dledger/src/main/java/io/openmessaging/storage/dledger/statemachine/StateMachineCaller.java
dledger/src/main/java/io/openmessaging/storage/dledger/store/file/DLedgerMmapFileStore.java
dledger/src/test/java/io/openmessaging/storage/dledger/LeaderElectorTest.java
dledger/src/test/java/io/openmessaging/storage/dledger/statemachine/register/RegisterStateMachine.java

close: https://github.com/openmessaging/dledger/issues/301

[ISSUE #301] Add entry type to distinguish the entry

---

dledger/pom.xml
dledger/src/main/java/io/openmessaging/storage/dledger/DLedgerConfig.java
dledger/src/main/java/io/openmessaging/storage/dledger/DLedgerEntryPusher.java
dledger/src/main/java/io/openmessaging/storage/dledger/DLedgerServer.java
dledger/src/main/java/io/openmessaging/storage/dledger/metrics/DLedgerMetricsConstant.java
dledger/src/main/java/io/openmessaging/storage/dledger/metrics/DLedgerMetricsManager.java
dledger/src/main/java/io/openmessaging/storage/dledger/metrics/MetricsExporterType.java
dledger/src/main/java/io/openmessaging/storage/dledger/metrics/NopLongCounter.java
dledger/src/main/java/io/openmessaging/storage/dledger/metrics/NopLongHistogram.java
dledger/src/main/java/io/openmessaging/storage/dledger/metrics/NopObservableLongGauge.java
dledger/src/main/java/io/openmessaging/storage/dledger/snapshot/SnapshotManager.java
dledger/src/main/java/io/openmessaging/storage/dledger/snapshot/SnapshotStore.java
dledger/src/main/java/io/openmessaging/storage/dledger/snapshot/file/FileSnapshotStore.java
dledger/src/main/java/io/openmessaging/storage/dledger/statemachine/StateMachineCaller.java
example/src/main/java/io/openmessaging/storage/dledger/example/register/RegisterDLedger.java
example/src/main/java/io/openmessaging/storage/dledger/example/register/command/RegisterCommand.java
pom.xml
script/deploy-three-register.sh

close: https://github.com/openmessaging/dledger/issues/307

[ISSUE #307] Support metrics

---

dledger/src/main/java/io/openmessaging/storage/dledger/DLedgerConfig.java
dledger/src/test/java/io/openmessaging/storage/dledger/AppendAndGetTest.java
dledger/src/test/java/io/openmessaging/storage/dledger/AppendAndPushTest.java
dledger/src/test/java/io/openmessaging/storage/dledger/BatchPushTest.java
dledger/src/test/java/io/openmessaging/storage/dledger/CommitIndexTest.java
dledger/src/test/java/io/openmessaging/storage/dledger/LeaderElectorTest.java
dledger/src/test/java/io/openmessaging/storage/dledger/ServerTestHarness.java
dledger/src/test/java/io/openmessaging/storage/dledger/WriteTest.java
dledger/src/test/java/io/openmessaging/storage/dledger/entry/DLedgerEntryCoderTest.java
dledger/src/test/java/io/openmessaging/storage/dledger/statemachine/MockSnapshotFile.java
dledger/src/test/java/io/openmessaging/storage/dledger/statemachine/RegisterSnapshotFile.java

e.g:
```
Assertions.assertTrue(false); => Assertions.fail();
```
```
Assertions.assertTrue(future instanceof AppendFuture); => Assertions.assertInstanceOf(AppendFuture.class, future);
```

code-format: optmize or simplify some code.
